Repository hpcgroup/pipit, pull requests merged in 2022-11, with the labels that each got.

#40 Trace: standardizing comm matrix
  pipit/trace.py
Labels: status: ready for review

#41 Tests: OTF2 Reader Unit Tests
  pipit/tests/conftest.py
  pipit/tests/otf2-tests.py
Labels: priority: urgent, status: ready for review

#30 reader: add Nsight reader
  docs/examples/nsight.py
  pipit/readers/nsight_reader.py
  pipit/trace.py
Labels: priority: high, status: ready for review, type: feature

#42 tests: unit test for the comm_matrix function
  pipit/tests/trace.py
Labels: priority: urgent, status: ready for review

#45 hpctoolkit reader: fixed sorting hpct trace by also sorting by index
  pipit/readers/hpctoolkit_reader.py
Labels: priority: high, status: ready for review
