Repository hpcgroup/pipit, pull requests merged in 2022-12, with the labels that each got.

#51 OTF2 Reader: Performance Improvements
  pipit/readers/otf2_reader.py
  pipit/trace.py
Labels: priority: high, status: ready for review, type: enhancement

#34 reader: add Projections reader
  docs/examples/projections.py
  pipit/readers/projections_reader.py
  pipit/trace.py
Labels: priority: high, status: ready for review

#55 Projections Reader - Updated event type to enter/leave
  pipit/readers/projections_reader.py
Labels: priority: urgent, status: ready for review

#58 OTF2 Reader: number threads similar to other trace formats
  pipit/readers/otf2_reader.py
Labels: status: ready for review
