Repository hpcgroup/pipit, pull requests merged in 2023-04, with the labels that each got.

#82 trace: add load imbalance function
  pipit/trace.py
Labels: priority: high, status: ready for review

#87 Trace: time profile
  pipit/tests/trace.py
  pipit/trace.py
Labels: priority: urgent, status: ready for review, type: feature

#81 bugfix: make _match_events also check name at the same depth
  pipit/trace.py
Labels: priority: high, status: ready for review, type: bug

#90 readers: add CSV reader
  docs/examples/csv_reader.py
  pipit/tests/data/foo-bar.csv
  pipit/trace.py
Labels: priority: normal, status: ready for review, type: feature
